# ─────────────────────────────────────────────
# Builder Stage
# ─────────────────────────────────────────────
FROM node:24-alpine AS builder

# Fix Alpine TLS issues (CI stability)
RUN sed -i 's|https://dl-cdn.alpinelinux.org|http://dl-cdn.alpinelinux.org|g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache git ffmpeg wget curl bash openssl dos2unix

WORKDIR /evo

# Copy entire project (since context = evo/)
COPY . .

# Install dependencies
RUN npm ci --silent
RUN ls -la ./Docker || true
# Prepare scripts
RUN if [ -d "./Docker/scripts" ]; then \
    chmod +x ./Docker/scripts/* && dos2unix ./Docker/scripts/*; \
    else \
    echo "No scripts directory found, skipping..."; \
    fi


RUN npm run build

# ─────────────────────────────────────────────
# Final Stage
# ─────────────────────────────────────────────
FROM node:24-alpine AS final

RUN apk add --no-cache tzdata ffmpeg bash openssl

ENV TZ=America/Sao_Paulo
ENV DOCKER_ENV=true

WORKDIR /evolution

COPY --from=builder /evolution/package.json ./package.json
COPY --from=builder /evolution/package-lock.json ./package-lock.json
COPY --from=builder /evolution/dist ./dist
COPY --from=builder /evolution/prisma ./prisma
COPY --from=builder /evolution/manager ./manager
COPY --from=builder /evolution/public ./public
COPY --from=builder /evolution/.env ./.env
COPY --from=builder /evolution/Docker ./Docker
COPY --from=builder /evolution/runWithProvider.js ./runWithProvider.js

# Install only production dependencies (no devDependencies)
RUN npm ci --omit=dev --silent

EXPOSE 8080

ENTRYPOINT ["/bin/bash", "-c", ". ./Docker/scripts/deploy_database.sh && npm run start:prod"]