services:
  api:
    container_name: evo_api
    image: evo/api:local
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evo_instances:/evo/instances
    networks:
      - evo-net
    env_file:
      - .env
    expose:
      - 8080

  frontend:
    container_name: evo_frontend
    image: evo/manager:local
    build: ./evo-manager-v2
    restart: always
    ports:
      - "3000:80"
    networks:
      - evo-net

volumes:
  evo_instances:


networks:
  evo-net:
    name: evo-net
    driver: bridge
