# ─────────────────────────────────────────────
# Builder Stage
# ─────────────────────────────────────────────
FROM node:24-alpine AS builder

# Fix Alpine TLS issues (CI stability)
RUN sed -i 's|https://dl-cdn.alpinelinux.org|http://dl-cdn.alpinelinux.org|g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache git ffmpeg wget curl bash openssl dos2unix

WORKDIR /evo

# Copy manifests first for better layer caching
COPY package*.json tsconfig.json tsup.config.ts ./

RUN npm ci --silent

# Copy entire project (since context = evo/)
COPY . .

COPY ./runWithProvider.js ./
COPY ./.env.example ./.env
COPY ./Docker ./Docker


# Prepare scripts
RUN if [ -d "./Docker/scripts" ]; then \
    chmod +x ./Docker/scripts/* && dos2unix ./Docker/scripts/*; \
    else \
    echo "No scripts directory found, skipping..."; \
    fi

RUN ./Docker/scripts/generate_database.sh

RUN npm run build

# ─────────────────────────────────────────────
# Final Stage
# ─────────────────────────────────────────────
FROM node:24-alpine AS final

RUN apk add --no-cache tzdata ffmpeg bash openssl

ENV TZ=America/Sao_Paulo
ENV DOCKER_ENV=true

WORKDIR /evo

COPY --from=builder /evo/package.json ./package.json
COPY --from=builder /evo/package-lock.json ./package-lock.json
COPY --from=builder /evo/node_modules ./node_modules

COPY --from=builder /evo/dist ./dist
COPY --from=builder /evo/prisma ./prisma
COPY --from=builder /evo/public ./public
COPY --from=builder /evo/.env ./.env
COPY --from=builder /evo/Docker ./Docker
COPY --from=builder /evo/manager ./manager
COPY --from=builder /evo/runWithProvider.js ./runWithProvider.js

# Install only production dependencies (no devDependencies)
RUN npm prune --omit=dev --silent

EXPOSE 8080

ENTRYPOINT ["/bin/bash", "-c", ". ./Docker/scripts/deploy_database.sh && npm run start:prod"]