[package]
name = "api-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

api_gateway = { path = "../../crates/api_gateway" }
pool_manager = { path = "../../crates/pool_manager" }
health_monitor = { path = "../../crates/health_monitor" }
shared = { path = "../../crates/shared" }
tracing.workspace = true
tracing-subscriber.workspace = true
